codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        enabled: yes
        target: auto
        threshold: 5%
        if_not_found: success
        if_ci_failed: error
    patch:
      default:
        target: 50%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no

ignore:
- "src/"
- "srcs/"
- "**.rds"
- "**.pdf"
- "R/gurobi.R" # ignore gurobi in diff as licensing makes unit testing difficult
