language: r
cache: packages
r: 4.2.0
warnings_are_errors: false
r_check_args: "--no-build-vignettes --no-manual --as-cran --no-examples"
before_install:
- curl -OL $URL
- mv jabba.tar.gz.gpg?dl=0 jabba.tar.gz.gpg
- echo $JAB | sudo gpg --passphrase-fd 0 jabba.tar.gz.gpg
- mkdir $HOME/my.cplex && tar -xvzf jabba.tar.gz --directory $HOME/my.cplex/
- curl -OL https://raw.githubusercontent.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- export R_REMOTES_NO_ERRORS_FROM_WARNINGS=TRUE
script: "./travis-tool.sh run_tests"
after_failure:
- "./travis-tool.sh dump_logs"
after_success:
- travis_wait Rscript -e 'covr::codecov()'
env:
  global:
  - CPLEX_DIR=$HOME/my.cplex/
  - CPLEX_INCLUDE_PATH=$HOME/my.cplex/include
  - CPLEX_LIB_PATH=$HOME/my.cplex/lib
  - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran --no-examples"
  - _R_CHECK_TESTS_NLINES_=0
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=TRUE
  - _R_CHECK_FORCE_SUGGESTS_=false
